# application
APPLICATION__DEBUG: 1
# cache
CACHE__DEFAULT__HOST: 127.0.0.1
CACHE__DEFAULT__PORT: 6379
CACHE__DEFAULT__PASSWORD:
CACHE__DEFAULT__DB: 0
CACHE__DEFAULT__TIMEOUT: 0
# database
DATABASE__DEFAULT__TYPE: mysql
DATABASE__DEFAULT__HOSTNAME: 114.215.190.171
DATABASE__DEFAULT__DATABASE: bx-hospital
DATABASE__DEFAULT__USERNAME: bx
DATABASE__DEFAULT__PASSWORD: bx2018
DATABASE__DEFAULT__DEBUG: true
DATABASE__DEFAULT__SQL_EXPLAIN: true
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# log
LOG__LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
LOG__ALLOW_KEY:
LOG__DEBUG: 1
LOG__RECORD_TRACE: 1
# msfoole
MSFOOLE__PORT: 9555
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 10
MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
MSFOOLE__WEBSOCKET__VI: 7AF3C134BEAA99E5
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__CHANNEL__SIZE: 65536
MSFOOLE__CHANNEL_POOL: 1
MSFOOLE__OPTION__WORKER_NUM: 1
MSFOOLE__OPTION__DAEMONIZE: 0
# pay
PAY__WEIFUTONG__URL: https://pay.swiftpass.cn/pay/gateway
PAY__WEIFUTONG__NOTIFY_URL: http://114.215.190.171:9666/Index/Payment/callbackWFT
PAY__WEIFUTONG__MCHID: 7551000001
PAY__WEIFUTONG__KEY: 9d101c97133837e13dde2d32a5054abb