# 生产环境配置
# application
APPLICATION__DEBUG: false
APPLICATION__ACCESS__ORIGIN: http://127.0.0.1:8080
APPLICATION__TOKEN__SWITCH: true
APPLICATION__TOKEN__CODE: true
# cache
CACHE__DEFAULT__HOST: 127.0.0.1
CACHE__DEFAULT__PORT: 6379
CACHE__DEFAULT__PASSWORD:
CACHE__DEFAULT__DB: 0
# cookie
COOKIE__PRIFIX: bx-
COOKIE__EXPIRE: 3600
COOKIE__PATH: /
COOKIE__DOMAIN:
COOKIE__TOKEN: token
COOKIE__AUTO_SELLING: 600
# database
DATABASE__DEFAULT__TYPE: mysql
DATABASE__DEFAULT__HOSTNAME: 127.0.0.1
DATABASE__DEFAULT__DATABASE: hospital
DATABASE__DEFAULT__USERNAME: root
DATABASE__DEFAULT__PASSWORD: root3306
DATABASE__DEFAULT__HOSTPORT: 3306
DATABASE__DEFAULT__DEBUG: false
DATABASE__DEFAULT__SQL_EXPLAIN: false
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# log
LOG__LEVEL: slow,info,notice,warning,error,critical,alert,emergency
LOG__ALLOW_KEY: 4E1681D4A89226D089EE57FA7C87E5F3,4E1681D4A89226D089EE57FA7C87E5F8
LOG__DEBUG: 0
LOG__RECORD_TRACE: 0
# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9666
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 600
MSFOOLE__WEBSOCKET__KEY: A89226D089EE57FA
MSFOOLE__WEBSOCKET__VI: 57EF7B0E6E582178
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__TABLE__SIZE: 1024
MSFOOLE__CHANNEL__SIZE: 2097152
MSFOOLE__CHANNEL__POOL: 2
MSFOOLE__OPTION__WORKER_NUM: 16
MSFOOLE__OPTION__MAX_REQUEST: 10000
MSFOOLE__OPTION__LOG_LEVEL: 3
MSFOOLE__OPTION__DAEMONIZE: 1
MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 10
MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 300
# openAPI
API__HOSPITAL__HOST: http://192.168.2.1:8080/mod_zykc_server
API__HOSPITAL__USER: 123
# pay
PAY__WEIFUTONG__URL: https://pay.swiftpass.cn/pay/gateway
PAY__WEIFUTONG__NOTIFY_URL: http://www.xdbxyy.com:34384/Index/Payment/callbackWFT
PAY__WEIFUTONG__MCHID: 160530012707
PAY__WEIFUTONG__KEY: 603896c8dcbbd062434533cc4d4ad51a