# application
APPLICATION__DEBUG: 0
# database
DATABASE__DEFAULT__HOSTNAME: 114.215.190.171
DATABASE__DEFAULT__DATABASE: bxhospital
DATABASE__DEFAULT__USERNAME: bxhospital
DATABASE__DEFAULT__PASSWORD: bx2018
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9666
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 60
MSFOOLE__WEBSOCKET__KEY: A89226D089EE57FA
MSFOOLE__WEBSOCKET__VI: 57EF7B0E6E582178
# openAPI
API__HOSPITAL__HOST: http://www.cdzykc.com/mod_zykc_server
API__HOSPITAL__USER: 123
# pay
PAY__WEIFUTONG__URL: https://pay.swiftpass.cn/pay/gateway
PAY__WEIFUTONG__NOTIFY_URL: http://114.215.190.171:9555/Index/Payment/callbackWFT
PAY__WEIFUTONG__MCHID: 7551000001
PAY__WEIFUTONG__KEY: 9d101c97133837e13dde2d32a5054abb