#CACHE__REDIS__HOST: 127.0.0.1
#CACHE__REDIS__PORT: 6379
#CACHE__REDIS__PASSWORD:
#CACHE__REDIS__DB: 0
#CACHE__REDIS__TIMEOUT: 0
#CACHE__REDIS__EXPIRE: 0
#CACHE__REDIS__PREFIX:
#CACHE__REDIS__SERIALIZE: 1
MSFOOLE__WEBSOCKET__KEY: A89226D089EE57FA
MSFOOLE__WEBSOCKET__VI: 57EF7B0E6E582178