# 生产环境配置
# application
APPLICATION__DEBUG: false
APPLICATION__ACCESS__ORIGIN: http://127.0.0.1:8080
APPLICATION__TOKEN__SWITCH: true
APPLICATION__TOKEN__CODE: true
# cache
CACHE__DEFAULT__HOST: 127.0.0.1
CACHE__DEFAULT__PORT: 6379
CACHE__DEFAULT__PASSWORD:
CACHE__DEFAULT__DB: 0
# cookie
COOKIE__PRIFIX: bx-
COOKIE__EXPIRE: 3600
COOKIE__PATH: /
COOKIE__DOMAIN:
COOKIE__TOKEN: token
COOKIE__AUTO_SELLING: 600
# database
DATABASE__DEFAULT__TYPE: mysql
DATABASE__DEFAULT__HOSTNAME: 127.0.0.1
DATABASE__DEFAULT__DATABASE: hospital
DATABASE__DEFAULT__USERNAME: root
DATABASE__DEFAULT__PASSWORD: root3306
DATABASE__DEFAULT__HOSTPORT: 3306
DATABASE__DEFAULT__DEBUG: false
DATABASE__DEFAULT__SQL_EXPLAIN: false
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# log
LOG__LEVEL: slow,info,notice,warning,error,critical,alert,emergency
LOG__ALLOW_KEY:
LOG__DEBUG: false
LOG__RECORD_TRACE: false
# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9666
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 600
MSFOOLE__WEBSOCKET__KEY: A89226D089EE57FA
MSFOOLE__WEBSOCKET__VI: 57EF7B0E6E582178
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__TABLE__SIZE: 1024
MSFOOLE__CHANNEL__SIZE: 2097152
MSFOOLE__CHANNEL__POOL: 2
MSFOOLE__OPTION__WORKER_NUM: 12
MSFOOLE__OPTION__MAX_REQUEST: 10000
MSFOOLE__OPTION__LOG_LEVEL: 3
MSFOOLE__OPTION__DAEMONIZE: 1
MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 5
MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 150
# openAPI
API__HOSPITAL__HOST: http://192.168.2.1:8080/mod_zykc_server
API__HOSPITAL__USER: 123
# pay
PAY__WEIFUTONG__URL: https://pay.swiftpass.cn/pay/gateway
PAY__WEIFUTONG__NOTIFY_URL: http://wap.xdbxyy.com/Index/Payment/callbackWFT
PAY__WEIFUTONG__MCHID: '160530012707'
PAY__WEIFUTONG__KEY: '603896c8dcbbd062434533cc4d4ad51a'
PAY__WEIFUTONG__OP_USER_ID: '33514891'
# wechat
WECHAT__BASEURL: http://wx.xdbxyy.com
WECHAT__OPTION__DEBUG: false
WECHAT__OPTION__TOKEN: Mcar2018
WECHAT__OPTION__ENCODINGAESKEY: LnOioxhxlwFDJ5sTR9zmRQ6qF97nG9HJI4pOygyEqD3
WECHAT__OPTION__APPID: wx2491c7bdfde11a19
WECHAT__OPTION__APPSECRET: ff32b80489ec6ba36b21ebc45dcab4c8
WECHAT__WELCOME: "欢迎使用成都北新医院微信公众平台，我们将竭诚为您服务！"
WECHAT__TEMPLATE__ORDER: "to7lTLB0_T7LKaLZtp_BqrZ2fh8G_qGRdK24s9BfXJc"
WECHAT__TEMPLATE__PAYMENT: "9Fx7GvCt7r7erU8EBqCs5yWph2SXsgefVlTqVhF9xIw"
WECHAT__TEMPLATE__HOSPITAL: "FVwq4rTynvgaJj_GMS8eg47ST6_r9Oi8tTS5n_L5i4k"
WECHAT__TEMPLATE__TODAY: "a91s_z9YJbhHvwi2UwrohZ378jd9lrKcNBbATXxnsGI"