# 开发环境配置
# application
APPLICATION__DEBUG: true
APPLICATION__ACCESS__ORIGIN: http://127.0.0.1:8080
APPLICATION__TOKEN__SWITCH: true
APPLICATION__TOKEN__CODE: true
# cache
CACHE__DEFAULT__HOST: 127.0.0.1
CACHE__DEFAULT__PORT: 6379
CACHE__DEFAULT__PASSWORD:
CACHE__DEFAULT__DB: 0
# cookie
COOKIE__PRIFIX: bx-
COOKIE__EXPIRE: 3600
COOKIE__PATH: /
COOKIE__DOMAIN:
COOKIE__TOKEN: token
COOKIE__AUTO_SELLING: 600
# database
DATABASE__DEFAULT__TYPE: mysql
DATABASE__DEFAULT__HOSTNAME: 114.215.190.171
DATABASE__DEFAULT__DATABASE: bx-hospital
DATABASE__DEFAULT__USERNAME: bx
DATABASE__DEFAULT__PASSWORD: bx2018
DATABASE__DEFAULT__HOSTPORT: 3306
DATABASE__DEFAULT__DEBUG: true
DATABASE__DEFAULT__SQL_EXPLAIN: true
# extra
EXTRA__SMS__KEY: b583e0692cd9dbc586ef
EXTRA__SMS__USER: zgsof
EXTRA__DD__HOOK: 84fe66b00d96a4492df3da0c3f8f49735c2b505c17c68f4f97cf77a73fda8336
# log
LOG__LEVEL: slow,sql,debug,info,notice,warning,error,critical,alert,emergency
LOG__ALLOW_KEY:
LOG__DEBUG: true
LOG__RECORD_TRACE: true
# msfoole
MSFOOLE__HOST: 0.0.0.0
MSFOOLE__PORT: 9555
MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
MSFOOLE__MONITOR__INTERVAL: 10
MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
MSFOOLE__WEBSOCKET__VI: 7AF3C134BEAA99E5
MSFOOLE__WEBSOCKET__SIGN: false
MSFOOLE__TABLE__SIZE: 1024
MSFOOLE__CHANNEL__SIZE: 65536
MSFOOLE__CHANNEL__POOL: 1
MSFOOLE__OPTION__WORKER_NUM: 1
MSFOOLE__OPTION__MAX_REQUEST: 0
MSFOOLE__OPTION__LOG_LEVEL: 0
MSFOOLE__OPTION__DAEMONIZE: 0
MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 150
# openAPI
API__HOSPITAL__HOST: http://www.cdzykc.com:53324/mod_zykc_server
API__HOSPITAL__USER: 123
# pay
PAY__WEIFUTONG__URL: https://pay.swiftpass.cn/pay/gateway
PAY__WEIFUTONG__NOTIFY_URL: http://45.40.202.228:9555/Index/Payment/callbackWFT
PAY__WEIFUTONG__MCHID: '7551000001'
PAY__WEIFUTONG__KEY: '9d101c97133837e13dde2d32a5054abb'
PAY__WEIFUTONG__OP_USER_ID: '7551000001'